meta:
  containers:
    ruby: &ruby-image-resource
      type: docker-image
      source:
        repository: ruby
        tag: 2.6.5-alpine3.10

groups:
  - name: "Build"
    jobs:
      - Trigger
      - Build
  - name: "Timer"
    jobs:
      - weekly-timer

jobs:
  - name: weekly-timer
    plan:
      - get: every-saturday-midnight
        trigger: true
      - put: pipeline-trigger
        params: { bump: patch }

  - name: Trigger
    plan:
      - in_parallel:
          - get: docker-xteve-repo
            trigger: true
          - get: xteve-repo
            trigger: true
          - get: alpine-release-feed
            trigger: true
          - put: pipeline-trigger
            params: { bump: patch }
  - name: Build
    public: true
    plan:
      - in_parallel:
          - get: docker-xteve-repo
            passed: [Trigger]
            trigger: true
          - get: xteve-repo
            passed: [Trigger]
            trigger: true
          - get: alpine-release-feed
            passed: [Trigger]
            trigger: true
          - get: pipeline-trigger
            trigger: true
          - put: metadata
      - task: Extract Versions
        config:
          platform: linux
          image_resource: *ruby-image-resource
          inputs:
            - name: xteve-repo
            - name: docker-xteve-repo
            - name: alpine-release-feed
            - name: metadata
          outputs:
            - name: build-args
            - name: tag
          run:
            path: sh
            args:
              - -e
              - -x
              - -c
              - |
                ruby docker-xteve-repo/ci/scripts/build-args.rb | tee build-args/build-args.json
                TAG=$(ruby docker-xteve-repo/ci/scripts/tag.rb)
                echo "${TAG}" | tee tag/tag
                ruby docker-xteve-repo/ci/scripts/build-args-curl.rb | tee build-args/build-args-curl.json
                echo "${TAG}-curl" | tee tag/tag-curl
                echo "latest-curl" | tee tag/tag-curl-latest
      - task: Do the Truffle Shuffle
        config:
          platform: linux
          image_resource: *ruby-image-resource
          inputs:
            - name: xteve-repo
            - name: docker-xteve-repo
          outputs:
            - name: docker-build-dir
          run:
            path: sh
            args:
              - -e
              - -x
              - -c
              - |
                cp -a xteve-repo docker-build-dir/
                cp docker-xteve-repo/Dockerfile* docker-build-dir/
      - task: Print some things for verification
        config:
          platform: linux
          image_resource: *ruby-image-resource
          inputs:
            - name: docker-build-dir
            - name: build-args
          outputs:
            - name: public-metadata
          run:
            path: sh
            args:
              - -e
              - -x
              - -c
              - |
                echo "## Docker Build args for this build"
                cat build-args/build-args.json
                echo "## Dockerfile that will be used for this build"
                cat docker-build-dir/Dockerfile
      - put: docker-xteve-image
        params:
          tags: ["qemu"]
          build: docker-build-dir
          buildx_platforms: "linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8"
          build_args_file: build-args/build-args.json
          tag_file: tag/tag
          tag_as_latest: true
      - put: docker-xteve-image
        params:
          tags: ["qemu"]
          build: docker-build-dir
          buildx_platforms: "linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8"
          build_args_file: build-args/build-args-curl.json
          dockerfile: docker-build-dir/Dockerfile.curl
          tag_file: tag/tag-curl
          additional_tags: tag/tag-curl-latest
          tag_as_latest: false
      - put: microbadger-webhook

resources:
  - name: docker-xteve-repo
    type: git
    icon: git
    source:
      uri: git@github.com:whi-tw/docker-xteve.git
      branch: master
      private_key: |
        ((concourse-ssh-key.id_rsa))

  - name: pipeline-trigger
    icon: check
    type: semver
    source: &version-repo-source
      driver: git
      uri: git@github.com:whi-tw/docker-xteve.git
      branch: pipeline-trigger
      private_key: |
        ((concourse-ssh-key.id_rsa))
      file: pipeline-trigger
      git_user: "Concourse <concourse@whitwell.dev>"
      initial_version: 0.0.0

  - name: every-saturday-midnight
    type: time
    icon: alarm
    source:
      start: "00:00"
      stop: "01:00"
      location: Europe/London
      days: [Saturday]

  - name: xteve-repo
    type: git
    icon: git
    source:
      uri: git@github.com:xteve-project/xTeVe.git
      branch: master
      tag_filter: "*.*"
      private_key: |
        ((concourse-ssh-key.id_rsa))

  - name: alpine-release-feed
    type: rss-resource
    icon: rss
    check_every: 6h
    source:
      url: "https://docker-hub-rss.now.sh/_/alpine.atom?exclude=latest%2Cedge&includeRegex=%5B0-9%5D%2B%5C.%5B0-9%5D%2B%5C.%3F%5B0-9%5D%3F"

  - name: docker-xteve-image
    type: docker-buildx-builder
    icon: docker
    source:
      repository: tnwhitwell/xteve
      username: ((docker-hub.username))
      password: ((docker-hub.password))

  - name: microbadger-webhook
    type: concourse-http-resource
    source:
      url: https://hooks.microbadger.com/images/tnwhitwell/xteve/_OzHj6z05iHNUjKZsCmOW62x0IE=
      method: "POST"

  - name: metadata
    type: metadata

resource_types:
  - name: docker-buildx-builder
    type: docker-image
    privileged: true
    source:
      repository: tnwhitwell/docker-buildx-resource
      tag: latest
  - name: concourse-http-resource
    type: docker-image
    source:
      repository: edtan1/concourse-http-resource
  - name: metadata
    type: docker-image
    source:
      repository: olhtbr/metadata-resource
  - name: rss-resource
    type: docker-image
    source:
      repository: tnwhitwell/concourse-rss-resource
      tag: latest
